name: df3d
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - scikit-learn
  - scipy
  - scikit-video
  - scikit-image
  - matplotlib
  - tqdm
  - colorama
  - progress
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.4
  - pip
  - pip:
    - PyQt5
    - opencv-python-headless
    - -e ../Drosophila2DPose
    - -e ../PyBundleAdjustment
    - -e .