name: test

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.12"]
      fail-fast: false

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install python v${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install git+https://github.com/NeLy-EPFL/DeepFly2D git+https://github.com/NeLy-EPFL/PyBundleAdjustment.git -e .
        sudo apt install ffmpeg -y

    - name: Run Tests
      run: |
        python -m unittest discover