name: test

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.9", "3.12"]
      fail-fast: false
    defaults:
      run:
        # these makes it so all steps automatically have our conda environment activated
        shell: bash -el {0}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Cache conda
      id: cache
      uses: actions/cache@v4
      with:
        path: ~/conda_pkgs_dir
        key:
          ${{ runner.os }}-conda-python${{ matrix.python-version }}-${{hashFiles('environment.yml') }}

    - name: Set up Conda (Python ${{ matrix.python-version }})
      uses: conda-incubator/setup-miniconda@v3
      with:
        activate-environment: df3d
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
        environment-file: environment.yml
        use-only-tar-bz2: true

    - name: hack to use system ffmpeg
      run: |
        conda remove ffmpeg --force

    - name: Conda info
      run: |
        conda info
        conda list

    - name: Run Tests
      run: |
        conda activate df3d
        python -m unittest